
#     snippet: studio-rpc-usb-uart
#     snippet: zmk-usb-logging
#     cmake-args: -DCONFIG_ZMK_STUDIO=y

---
include:
  - board: rpi_pico
    shield: KD_Apple
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    
